version: '3.8'

services:
  ocr-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: soumya1974/ocr_service:latest
    container_name: legal_metrology_ocr
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-groq/compound}
    env_file:
      - .env
